name: nizvpn
description: Simple VPN using Platform Channel
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^5.0.16
  firebase_crashlytics: ^0.1.4+1
  google_fonts: ^1.1.0
  provider: ^4.3.2
  dio: ^3.0.10
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  shared_preferences: ^0.5.8
  line_icons: ^0.2.0
  ndialog: ^2.1.2
  flutter_inapp_purchase: ^2.2.0
  admob_flutter: "^0.3.4"
  in_app_update: ^1.1.11
  in_app_review: ^0.2.0+3
  package_info: ^0.4.3
  share: ^0.6.4+5
  url_launcher: ^5.5.0
  firebase_admob: ^0.9.3+4
  device_info: ^0.4.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/icons/"
    - "assets/icons/flags/"
  fonts:
    - family: NerdVPNIcon
      fonts:
        - asset: assets/fonts/NerdVPNIcon.ttf

